development:
  adapter: mysql2
  encoding: utf8
  database: omeme_dev
  username: root
  password: 
  host: localhost
  timeout: 5000

test:
  adapter: mysql2
  encoding: utf8
  database: omeme_test
  username: root
  password: 
  host: localhost
  timeout: 5000

production:
  adapter: mysql2
  encoding: utf8
  database: omeme
  username: omeme
  password: omeme
  host: localhost
  timeout: 5000